---
config:
  theme: neo-dark
  layout: dagre
  look: neo
---
flowchart TB
 subgraph BOT["BOT"]
        recebeDados["Receber email com: <br>- dados do card<br>- instruções"]
  end
    Start["Início"] --> FluxoBitrix["Iniciar o Fluxo do Bitrix"]
    FluxoBitrix --> n1["Move para fase (Aguardando Pagamento)"]
    EnviarEmail["Enviar E-mail com dados do Card"] --> BOT
    CheckCPF{"CPF Vazio?"} -- Sim --> MsgErroCPF[/"Adiciona comentário no card:<br>Dados faltantes"/]
    MsgErroCPF --> Fim["Fim"]
    CheckCPF -- Não --> n2["Encerra Fluxo no Bitrix"]
    StartBrowser["Inicia monitoramento 24h Assíncrono no servidor"] --> Goto["Acessa o Portal"]
    Goto --> SearchBar["Verifica o pagamento"]
    SearchBar --> CheckGarantia{"Pagamento Confirmado?"}
    CheckGarantia -- Sim --> LogSuccess[/"Altera o campo PAGAMENTO ICATU para CONFIRMADO"/]
    LogSuccess --> ClickGarantia["Ativa Gatilho"]
    ClickGarantia --> CloseBrowserSUCCESS["Move p/ fase PAGAMENTO CONFIRMADO"]
    CloseBrowserSUCCESS --> End(["Fim"])
    CheckSolicitacao@{ label: "Existe 'Solicitação'?" } -- |Sim| --> LogInfo["Altera campo PAGAMENTO ICATU para PENDENTE"]
    BOT --> CheckCPF
    n1 --> EnviarEmail
    n2 --> StartBrowser
    CheckGarantia -- Não --> CheckSolicitacao
    LogInfo --> CheckGarantia
    CheckSolicitacao -- Não --> n5["Adiciona comentário ao CARD:<br>Solicitação não encontrada no ICATU"]
    n5 --> n6(["Fim"])

    Start@{ shape: start}
    CheckSolicitacao@{ shape: diam}
     Start:::start
     MsgErroCPF:::error
     Fim:::terminal
     Fim:::error
     LogSuccess:::success
     ClickGarantia:::rect
     ClickGarantia:::success
     CloseBrowserSUCCESS:::success
     End:::success
     CheckSolicitacao:::diamond
     CheckSolicitacao:::warning
     LogInfo:::lean-r
     LogInfo:::warning
     n5:::error
     n6:::error
    classDef warning color:#FFFFFF, fill:#f68520, stroke:#fff, stroke-width:2px
    classDef success color:#FFFFFF, fill:#00C853, stroke:#fff, stroke-width:2px
    classDef error color:#FFFFFF, fill:#c11e2e, stroke:#fff, stroke-width:2px